"""empty message

Revision ID: ad6f39373297
Revises: f3fde93eb7b7
Create Date: 2019-07-26 14:36:16.702291

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad6f39373297'
down_revision = 'f3fde93eb7b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'genre', ['name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'genre', type_='unique')
    # ### end Alembic commands ###
