"""empty message

Revision ID: e8af43894a97
Revises: d0dc40c61f8d
Create Date: 2019-07-26 10:10:42.831441

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e8af43894a97'
down_revision = 'd0dc40c61f8d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('movie',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('popularity', sa.Float(), nullable=False),
    sa.Column('director', sa.String(length=255), nullable=False),
    sa.Column('imdb_score', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('movie')
    # ### end Alembic commands ###
